---
title: "kaggle_meta_eda"
author: "Hongxu Zhu"
always_allow_html: yes
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    toc: yes
    toc_collapsed: yes
    toc_float: yes
---

```{r alternative-preambles,echo=FALSE,include=FALSE,eval=FALSE}
## if using word replace output with
output:
  word_document:
    toc: yes

## if using pdf replace output with
output:
  pdf_document:
    toc: yes
header-includes:
  - \usepackage{xcolor}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## colorizes text when using html or pdf output
## just spits out text x for word
colorize <- function(x, color) {
  if(color=="todo"){
    color <- "red"
    x <- paste0("TODO: ",x)
  }
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

todo <- function(x){
  paste0("**",colorize(x,"todo"),"**")
}

library(kableExtra)
library(cmapR)
library(edgeR)
library(arrow)
```
## Load metadata

```{r}
de_train_meta <- read_parquet("datasets/de_train.parquet")
id_map <- read.csv("datasets/id_map.csv")
adata_obs_meta <- read.csv("datasets/adata_obs_meta.csv")
```

Donor vs plate

```{r}
unique(adata_obs_meta$plate_name[adata_obs_meta$donor_id=="donor_0"])
unique(adata_obs_meta$plate_name[adata_obs_meta$donor_id=="donor_1"])
unique(adata_obs_meta$plate_name[adata_obs_meta$donor_id=="donor_2"])
```

Plate vs library

```{r}
plate_name <- unique(adata_obs_meta$plate_name)
library_id_list <- list()
for (i in 1:length(plate_name)){
  library_id_list[[i]] <- unique(adata_obs_meta$library_id[adata_obs_meta$plate_name==plate_name[i]])
}
```

Compounds info

147 = 144 + 2 positive + 1 negative

```{r}
compounds_df = data.frame(adata_obs_meta[,-(1:9)])
```

## Load expression data

```{r}
adata_train <- read_parquet("datasets/adata_train.parquet")
```













